apiVersion: v1
kind: Service
metadata:
  name: dns-lb
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: dns-lb-tcp
      port: 53
      targetPort: 53
    - protocol: UDP
      name: dns-lb-udp
      port: 53
      targetPort: 53