repositories:
- name: jetstack
  url: https://charts.jetstack.io
- name: harbor
  url: https://helm.goharbor.io
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

releases:
#  - name: ingress-nginx
#    namespace: ingress-nginx
#    createNamespace: true
#    labels:
#      app: ingress-nginx
#    wait: true
#    chart: ingress-nginx/ingress-nginx
#    version: 4.4.0
#    values:
#      - controller:
#          service:
#            type: NodePort

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    labels:
      app: cert-manager
    wait: true
    chart: jetstack/cert-manager
    version: v1.11.0
    set:
      - name: installCRDs
        value: "true"
  
  - name: harbor
    namespace: harbor
    createNamespace: true
    labels:
      app: harbor
    wait: true
    chart: harbor/harbor
    version: v1.12.0
    values:
      - envs/harbor/values.yaml