apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework
spec:
  scope: Namespaced
  group: otus.homework
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            spec:
              type: object
              properties:
                database:
                  type: string
                image:
                  type: string
                password:
                  type: string
                storage_size:
                  type: string
                usless_data:
                  type: string
              required:
              - database
              - image
              - password
  names:
    kind: MySQL
    plural: mysqls
    singular: mysql
    shortNames:
    - ms