alertmanager:
  enabled: false

grafana:
  enabled: true
  namespaceOverride: ""
  defaultDashboardsTimezone: Europe/Moscow
  adminPassword: admin
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      kubernetes.io/ingress.class: nginx
    hosts:
       - grafana.home.ru
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
      annotations: {}
      multicluster:
        global:
          enabled: false
        etcd:
          enabled: false
      provider:
        allowUiUpdates: false
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      isDefaultDatasource: true
  deleteDatasources:
    - name: loki
      orgId: 1
  additionalDataSources:
    - name: loki
      type: loki
      access: proxy
      org_id: 1
      url: http://loki:3100
      version: 1
      editable: false

prometheus:
  enabled: true
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      kubernetes.io/ingress.class: nginx
    hosts:
      - prom.home.ru
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false